### ISSUE TITLE
Infinite recursion in `get_comm` definition

### ISSUE THREAD

**Issue by amartinhuertas** [gridap/GridapDistributed.jl#13]
Hi @fverdugo ...

the following construction:

```julia
# return an object for which
# its restriction to the parts of a communicator is defined.
# The returned object is not necessarily an instance
# of DistributedData
# Do nothing by default.
function get_distributed_data(object)
  object
end

get_comm(a) = get_comm(get_distributed_data(a))
```

leads to infinite recursion with the default definition of `get_distributed_data`, if `get_comm` is not defined. Here I foresee two possible options (perhaps there are more):

1. `get_distributed_data` becomes an `@abstractmethod`.
or
2. `get_comm` becomes an `@abstractmethod`.

On the other hand, at several places, we have sentences like: `comm = get_comm(get_distributed_data(first(args)))`. Arent these latter ones somehow redundant if we keep the current definition of `get_comm`?

To be honest, I do not understand the overall logic of the interplay of `get_distributed_data` and `get_comm` ...

**Comment by fverdugo** [comment]
Hi @amartinhuertas 

I would adopt option 1 
>  `get_distributed_data` becomes an `@abstractmethod`.

and implement  `get_distributed_data` when needed.

`get_distributed_data` allows objects that wrap other objects that are "distributed data" to behave themselves as "distributed data". See, e.g., `DisributedDiscreteModel`. By "distributed data" I mean any object for which its restriction to a part is defined (note that NOT all objects that behave as "distributed data" inherit from `DistributedData` since it is not possible in general due the lack of multiple inheritance in Julia). 


For the usage of `get_distributed_data` consider this example:

```julia
struct Foo{T}
 data::DistributedData{D}
end
```

At this point the restriction of `Foo` objects to a part it is not defined. But, you can incorporate this behavior, e.g., as

```julia
get_distributed_data(a::Foo) = a.data
```
Now, restricting a `Foo` object to a part it is equivalent to restrict the field `data`.

It many situation it is way more convenient to define just one function (i.e., `get_distributed_data`) than define a bunch of methods to make `Foo` behave as "distributed data".

Hope it helps!

**Comment by amartinhuertas** [comment]
Thanks for the detailed exposition. I understand much better now. 

However, I still do not get the following comment in the source code:

```julia
...
# The returned object is not necessarily an instance
# of DistributedData
...
```
why this is useful/suitable/possible?

On the other hand, just to double-check, do you agree that that sentences like `comm = get_comm(get_distributed_data(first(args)))` that are spread all over the code are redundant?

**Comment by amartinhuertas** [comment]
> I would adopt option 1

I will do this.

**Comment by fverdugo** [comment]
> However, I still do not get the following comment in the source code:
```...
# The returned object is not necessarily an instance
# of DistributedData
...
```
> why this is useful/suitable/possible?

For instance, you can implement some methods so that a `DArray` (from the DistributedArrays package) behaves as "distributed data". However, `DArray` has already its type signature defined and will never be possible for a `DArray` inherit from `DistributedData`

**Comment by fverdugo** [comment]
In other situations, you will have distributed vector for linear algebra and you want these types inherit from `AbstractVector` instead of  `DistributedData`.

**Comment by fverdugo** [comment]
In summary, when you need multiple inheritance and/or extend previously existing types, a solution is to use duck typing + documentation

**Comment by amartinhuertas** [comment]
Yeah, I already understand the purpose of `get_distributed_data(a)` (much better after your exposition above). However, looking at the code comment carefully, in which context would `get_distributed_data(a)` return an object of a type that does not extend `DistributedData`?

**Comment by fverdugo** [comment]
> However, looking at the code comment carefully, in which context would get_distributed_data(a) return an object of a type that does not extend DistributedData?

E.g., the sequential communicator defines how  `Vector{T}` objects are restricted to a part. This allows you to do
```julia
comm = SequentialCommunicator(nparts)
v = rand(10)
do_on_parts(comm,v) do part, v_part
  v === v_part
end
``` 

`do_on_parts` will eventually call `get_distributed_data` for the vector `v`, which in this case should return `v` which is not at instance of `DistributedData`

**Comment by fverdugo** [comment]
in summary,  `get_distributed_data(object)` should return `object` if this object as "distributed data" behavior.

We can improve this with a "trait" like this

``` julia
function get_distributed_data(object)
  get_distributed_data(object,DistributedDataStyle(object))
end

get_distributed_data(object,::Val{true}) = object 
get_distributed_data(object,::Val{false}) = @abstractmethod
```

This is a common pattern in Julia

If you want we can discuss this face to face
