### ISSUE TITLE
Distributed ZeroMeanFESpace

### ISSUE THREAD

**Issue by JordiManyer** [gridap/GridapDistributed.jl#154]
The zeromean constraint is not working properly in distributed. See the following MWE:

```julia
using Gridap
using Gridap.ReferenceFEs, Gridap.Geometry, Gridap.Arrays, Gridap.FESpaces

using GridapDistributed, PartitionedArrays

np = (2,1)
ranks = with_debug() do distribute
  distribute(LinearIndices((prod(np),)))
end

nc = (6,1)
dmodel = CartesianDiscreteModel(ranks,np,(0,1,0,1),nc)

reffe = ReferenceFE(lagrangian,Float64,1)
V = TestFESpace(model,reffe;constraint=:zeromean)
dV = TestFESpace(dmodel,reffe;constraint=:zeromean)

gids = partition(get_free_dof_ids(dV))

map(local_views(dV),gids) do Vk, ids
  cell_lids = collect(Vector{Int},get_cell_dof_ids(Vk))
  cell_gids = lazy_map(Broadcasting(PosNegReindex(local_to_global(ids),[-1])),cell_lids)
  println(local_to_global(ids))
  display(cell_gids)
  println("-----")
end;
```

which prints the following: 

```julia
----- Processor 1:

loc_to_glob = [1, 2, 3, 7, 8, 4, 5, 6, 11]

connectivity = 
 [1, 2, 4, 5]
 [2, 3, 5, 6]
 [3, 7, 6, 11]
 [7, 8, 11, -1]

----- Processor 2:

loc_to_glob = [3, 7, 8, 9, 10, 6, 11, 12, 13]

connectivity = 
 [3, 7, 6, 11]
 [7, 8, 11, 12]
 [8, 9, 12, 13]
 [9, 10, 13, -1]
-----
```

which is clearly not what we expect. In processor 1, the last dof is fixed, which corresponds to global dof 12 in processor 2. It also should be also fixed in processor 2, but it is not the case. Basically we are fixing a zero mean within each processor (which also results in a global zero mean, but has a higher number of constraints).

**Comment by amartinhuertas** [comment]
Hi @JordiManyer. Thanks for reporting. I am not sure who/how ZeroMean has been implemented in the latest version of GridapDistributed. However, I implemented it in an earlier version, and I think I implemented it correctly. Please see: https://github.com/gridap/GridapDistributed.jl/issues/39#issuecomment-1027780435 for more details.

**Comment by JordiManyer** [comment]
So we concluded that this existed in v0.1, but was forgotten during the refactoring for v0.2.
