### ISSUE TITLE
Wrong `num_cells` for `DistributedTriangulations` with ghost cells

### ISSUE THREAD

**Issue by Jai-Tushar** [gridap/GridapDistributed.jl#159]
If the `DistributedTriangulation` has overlapping host cells, the following code counts some cells several times: 

```julia
function Geometry.num_cells(a::DistributedTriangulation)
  sum(map(trian->num_cells(trian),local_views(a)))
end
```

**Comment by JordiManyer** [comment]
I think in practice this is only used for display functions, but it is certainly a bug. It should be fixed by #160
