### ISSUE TITLE
Upgrade to Gridap 1.6 issues

### ISSUE THREAD

**Issue by amartinhuertas** [gridap/GridapDistributed.jl#31]
Hi @fverdugo, @santiagobadia, 

FYI ... in PR https://github.com/gridap/GridapDistributed.jl/pull/32, I ported `GridapDistributed.jl` to `Gridap 0.16.3`. Along the process, I annotated a set of concerns that you can find in the list below. Apart from solving this, I think it would be great to speak about which are the priorities/future plans with the development of `GridapDistributed.jl`.

## Several concerns I have detected along the process.

- `SparseMatrixAssembler` in `Gridap` v0.16 does no longer conceptually hold test and trial FE spaces inside, while  `DistributedSparseMatrixAssembler` does.
- Introduction of `ArtificeSparseMatrixToLeverageDefaults`. Something more clever to solve this issue?
- Review the need for the `allocate_local_vector` function and the workflow associated to it. Is there a better way to design this taking into account the way assembly operations have been redesigned in `Gridap` v0.16?
- I am skipping `symbolic_loop_vector!` all the way through.
- **[Solved in cc56f4decd425ad868fecca883b6b0eac931edfe]** Bilinear and linear functions for multifield problems cannot be iterated over (i.e., tuples) as in `Gridap`.
- I had to recover `Reindexed` and some of the associated machinery from Gridap 0.14.3. I need it for `GridapDistributed.jl`. Should we bypass this need? If yes, how?
- Review `DistributedFEFunction`s and their current hierarchy.
- `Gridap.Algebra.add_entry!`: We are inserting entries one by one. To see how we can introduce all cell entries at once with the new assembly interface.

**Comment by amartinhuertas** [comment]
@fverdugo ... FYI ... I had a meeting yesterday with @santiagobadia related to this issue. We agreed to proceed with the following tasks (in order of priority):

1. Explore a high-level API  for `GridapDistributed.jl` that follows as much as possible the one of `Gridap.jl`.
2. Develop new specialization of `GridapDistributed.jl` types and functions (`DistributedData`, `DistributedIndexSet`, etc.)  using `PartitionedArrays.jl` as back-end.
3. Implement a first prototype non-overlapping balancing domain decomposition preconditioner.
4. To study what is really needed from `GridapDistributedPETScWrappers.jl` and to include it into `GridapPETSc.jl` (less priority).

**Comment by fverdugo** [comment]
Sounds good. For the BDDC part, one needs to add some multi-level data structures in PartitionedArrays.

**Comment by amartinhuertas** [comment]
> Sounds good. For the BDDC part, one needs to add some multi-level data structures in PartitionedArrays.

Ok. Perhaps when I am about to start this work (I am about to start point 2. above now) it might help to have a meeting so that we may exchange ideas in this regard.
