### ISSUE TITLE
Missing DistributedData.jl file

### ISSUE THREAD

**Issue by amartinhuertas** [gridap/GridapDistributed.jl#5]
Hi @fverdugo ! ... I guess that in commit b39ed642ac2f641316ff1e4a6339649276d931b4 you forgot to add the `DistributedData.jl` file. This is what I get when I execute `using GridapDistributed` in the Julia REPL:

`
[ Info: Precompiling GridapDistributed [f9701e48-63b3-45aa-9a63-9bc6c271f355]
ERROR: LoadError: could not open file /home/amartin/git-repos/GridapDistributed.jl/src/DistributedData.jl
`

**Comment by fverdugo** [comment]
Solved via 5230c01c3f3e1104bad87230a12dfe8e249a9ada
