### ISSUE TITLE
Use mpiexecjl

### ISSUE THREAD

**Issue by eschnett** [gridap/GridapDistributed.jl#56]
`MPI.jl` comes with a wrapper for `mpiexec`, called `mpiexecjl`. See [here](https://juliaparallel.github.io/MPI.jl/stable/configuration/). Could this be used instead of the instructions given in the README here?

**Comment by amartinhuertas** [comment]
> Could this be used instead of the instructions given in the README here?

Hi @eschnett. I did not try. But it would be certainly a better solution. I will try and update the README.md accordingly. Thanks!

**Comment by amartinhuertas** [comment]
Done in https://github.com/gridap/GridapDistributed.jl/commit/b372b82584fffa802a93c776830ac39be6289813
