### ISSUE TITLE
Last travis CI build from 2 days ago

### ISSUE THREAD

**Issue by amartinhuertas** [gridap/GridapDistributed.jl#6]
Hi @fverdugo ... we realized that the last Travis build is from 2 days ago: https://travis-ci.com/github/gridap/GridapDistributed.jl

Do u know whether this is the expected behaviour? Did you deactivate it? Thanks!

**Comment by fverdugo** [comment]
It seems it was an indentation problem in .travis.yml

solved via 712a627b4e5df2f6a95732c0f45fa04533115ace
