### ISSUE TITLE
Treatment of Dirichlet values

### ISSUE THREAD

**Issue by oriolcg** [gridap/GridapDistributed.jl#68]
There are no `interpolate_dirichlet` and `interpolate_everywhere` functions implemented. Is there any particular reason for that? Does it need to be implemented?

**Comment by amartinhuertas** [comment]
Hi @oriolcg,

I would say there is no particular reason but that they have not been implemented yet. Indeed, we identified this as a pending task in issue https://github.com/gridap/GridapDistributed.jl/issues/39, under the "Low priority" section. 

I guess that you need them in `GridapODEs`, right?

**Comment by oriolcg** [comment]
Hi @amartinhuertas, thanks for pointing it out. Yes, this is needed for `GridapODEs`. Not only these functions but the ability to handle FE spaces with time-dependent Dirichlet boundary conditions.

If you think it's an easy task, I can try to implement it if I find some times in the coming days.

**Comment by amartinhuertas** [comment]
> If you think it's an easy task, I can try to implement it if I find some times in the coming days.

Let me take a look at the implementation difficulty, and I will come back to you.

**Comment by fverdugo** [comment]
> Is there any particular reason for that? 

As @amartinhuertas said, it was just a matter of resources and priorities. I think it should be quite easy to implement.

**Comment by amartinhuertas** [comment]
Addressed in PR https://github.com/gridap/GridapDistributed.jl/pull/74
