### ISSUE TITLE
Tutorials that show-case all building blocks in action

### ISSUE THREAD

**Issue by amartinhuertas** [gridap/GridapDistributed.jl#75]
cc @fverdugo @oriolcg 

To not forget. I think it would be great to write some tutorials showcasing all building blocks in action (GridapGmsh, GridapDistributed, GridapP4est, GridapPETsc). At present, we have the building blocks there, and a set of test/examples, but everything is not that well tighted together in a single place.

- [x] Add link to tutorial on GridapDistributed once it is already on `main`.

**Comment by oriolcg** [comment]
And GridapODEs... Indeed, it would be nice to have a nice example/tutorial with everything together. Maybe a standalone repo that could be used as a template for different applications?

**Comment by amartinhuertas** [comment]
Yes, using GridapODEs would be nice as well. 

I am going to add a first sketch of a tutorial for a steady state case (Poisson) in the Tutorials repo. 

Then we can talk about improvements, better organization of the tutorials repo, etc.

**Comment by amartinhuertas** [comment]
Started working on this here https://github.com/gridap/Tutorials/pull/128

**Comment by amartinhuertas** [comment]
Solved in https://github.com/gridap/Tutorials/pull/128. I have opened another issue https://github.com/gridap/Tutorials/issues/129
